export const ACHIEVEMENTS = [
  {
    id: "first-victory",
    title: "初战告捷",
    description: "赢得第一场战斗",
    icon: "battle",
    category: "combat",
  },
  {
    id: "boss-slayer",
    title: "首领斩击",
    description: "击败一名首领",
    icon: "elite",
    category: "combat",
  },
  {
    id: "flawless-victory",
    title: "无伤之战",
    description: "在一场战斗中不受到任何英雄伤害",
    icon: "shieldbearer",
    category: "combat",
  },
  {
    id: "ten-battles",
    title: "身经十战",
    description: "累计赢得 10 场战斗",
    icon: "battle",
    category: "combat",
    progress: { key: "battlesWon", target: 10 },
  },
  {
    id: "ritual-master",
    title: "仪式大师",
    description: "在一场战斗中完成全部三阶段仪式",
    icon: "life-oracle",
    category: "combat",
  },
  {
    id: "mercy-bandit",
    title: "仁者之心",
    description: "收编匪首，令其戴罪立功",
    icon: "peaceful",
    category: "story",
  },
  {
    id: "truth-seeker",
    title: "真相追寻者",
    description: "在第二章查账线中获得账册护卫",
    icon: "inquisitor",
    category: "story",
  },
  {
    id: "grave-digger",
    title: "掘墓人",
    description: "在第三章中选择挖掘佩特里的坟墓",
    icon: "bone-soldier",
    category: "story",
  },
  {
    id: "protect-innocent",
    title: "守护无辜",
    description: "在第五章中选择保护流民庙宇",
    icon: "shelter",
    category: "story",
  },
  {
    id: "face-the-lord",
    title: "大殿对峙",
    description: "在第六章中选择携证据归返与公爵对质",
    icon: "crown",
    category: "story",
  },
  {
    id: "oath-keeper",
    title: "守誓者",
    description: "在第三章后选定誓约",
    icon: "oath",
    category: "story",
  },
  {
    id: "justice-ending",
    title: "正义的代价",
    description: "达成正义结局「新的守护者」",
    icon: "oath",
    category: "story",
  },
  {
    id: "loyalty-ending",
    title: "沉默的骑士",
    description: "达成普通结局「未竟的誓言」",
    icon: "duelist",
    category: "story",
  },
  {
    id: "tragedy-ending",
    title: "灰烬中的誓言",
    description: "达成悲剧结局",
    icon: "greatsworder",
    category: "story",
  },
  {
    id: "fallen-ending",
    title: "长夜未尽",
    description: "在旅途中战败倒下",
    icon: "shadow-wolf",
    category: "story",
  },
  {
    id: "full-codex",
    title: "万象图鉴",
    description: "解锁全部卡牌图鉴",
    icon: "cards",
    category: "collection",
  },
  {
    id: "three-relics",
    title: "战具收藏家",
    description: "单次旅程获得 3 件战具",
    icon: "relic",
    category: "collection",
  },
  {
    id: "rich-merchant",
    title: "灰烬商人",
    description: "单次旅程累计花费 200 灰烬",
    icon: "shop",
    category: "collection",
  },
  {
    id: "all-endings",
    title: "命运的每一面",
    description: "解锁全部结局",
    icon: "story",
    category: "mastery",
    progress: { key: "endings", target: 5 },
  },
  {
    id: "full-health-boss",
    title: "圣焰不熄",
    description: "以满圣焰状态进入一场首领战",
    icon: "health",
    category: "mastery",
  },
];

export const ACHIEVEMENT_CATEGORIES = [
  { key: "combat", label: "战斗", icon: "battle" },
  { key: "story", label: "剧情", icon: "story" },
  { key: "collection", label: "收集", icon: "cards" },
  { key: "mastery", label: "精通", icon: "elite" },
];