import { CARD_ICONS } from "./card-icons.js";

/** @typedef {import("../types.js").CardDef} CardDef */

/** @type {readonly CardDef[]} */
export const GREY_KNIGHT_STARTER_DECK = [
  {
    attack: 2,
    cost: 1,
    health: 1,
    icon: CARD_ICONS.scout,
    id: "scout",
    nameEn: "Scout",
    name: "斥候",
    text: "轻装先行，探明敌阵的软肋。",
    flavor: "灰骑士的剑，总先到一步。",
  },
  {
    attack: 1,
    cost: 1,
    health: 3,
    icon: CARD_ICONS["ember-squire"],
    id: "ember-squire",
    nameEn: "Ember Squire",
    name: "灰烬侍从",
    onDeploy: [{ count: 1, kind: "energy" }],
    text: "入场：获得 1 点圣力。",
    flavor: "灰烬里的余火，也能点燃圣焰。",
  },
  {
    attack: 1,
    cost: 1,
    health: 2,
    icon: CARD_ICONS.herald,
    id: "herald",
    nameEn: "Herald",
    name: "号令者",
    onDeploy: [{ count: 1, kind: "draw" }],
    text: "入场：抽 1 张牌。",
    flavor: "号角之前，先有信使。",
  },
  {
    attack: 3,
    cost: 2,
    health: 1,
    icon: CARD_ICONS.arbalist,
    id: "arbalist",
    nameEn: "Arbalist",
    name: "弩手",
    onDeploy: [{ count: 1, kind: "damageHero" }],
    text: "入场：射出弩矢，灼伤对手英雄 1 点。",
    flavor: "一发入魂，先声夺人。",
  },
  {
    attack: 2,
    cost: 2,
    health: 2,
    icon: CARD_ICONS.duelist,
    id: "duelist",
    keyword: "firstStrike",
    nameEn: "Duelist",
    name: "决斗士",
    text: "先手。",
    flavor: "他总比深渊的影子快一步。",
  },
  {
    attack: 3,
    cost: 2,
    health: 2,
    icon: CARD_ICONS.swordsman,
    id: "swordsman",
    nameEn: "Swordsman",
    name: "剑士",
    text: "制式长剑，可靠的杀法。",
    flavor: "队列里最安静的一把剑。",
  },
  {
    attack: 1,
    cost: 2,
    health: 4,
    icon: CARD_ICONS.shieldbearer,
    id: "shieldbearer",
    nameEn: "Shieldbearer",
    name: "盾卫",
    text: "举盾者即是城墙。",
    flavor: "他的盾，比城墙更硬。",
  },
  {
    attack: 2,
    cost: 3,
    health: 3,
    icon: CARD_ICONS.inquisitor,
    id: "inquisitor",
    nameEn: "Inquisitor",
    name: "审判官",
    onDeploy: [{ count: 2, kind: "damageHero" }],
    text: "入场：掷出审判圣印，灼伤对手英雄 2 点。",
    flavor: "灰骑士的怒火，有名有姓。",
  },
  {
    attack: 2,
    cost: 3,
    health: 5,
    icon: CARD_ICONS["bastion-knight"],
    id: "bastion-knight",
    nameEn: "Bastion Knight",
    name: "壁垒骑士",
    text: "钉在阵线上，一步不退。",
    flavor: "壁垒由活人铸成。",
  },
  {
    attack: 4,
    cost: 3,
    health: 3,
    icon: CARD_ICONS.greatsworder,
    id: "greatsworder",
    nameEn: "Greatsworder",
    name: "巨剑士",
    text: "一剑开出一条路。",
    flavor: "他的剑宽得能当盾使。",
  },
];

/** @type {readonly CardDef[]} */
export const ABYSS_FRONT_ENEMIES = [
  {
    attack: 1,
    cost: 0,
    health: 1,
    icon: CARD_ICONS["abyss-wraith"],
    id: "abyss-wraith",
    name: "怨灵",
    text: "一声叹息凝成的影子。",
  },
  {
    attack: 2,
    cost: 0,
    health: 2,
    icon: CARD_ICONS["shadow-wolf"],
    id: "shadow-wolf",
    name: "影狼",
    text: "从圣焰照不到的角落扑来。",
  },
  {
    attack: 1,
    cost: 0,
    health: 3,
    icon: CARD_ICONS["bone-soldier"],
    id: "bone-soldier",
    name: "骸卒",
    text: "骨头里还记着冲锋的口令。",
  },
  {
    attack: 2,
    cost: 0,
    health: 3,
    icon: CARD_ICONS["light-eater"],
    id: "light-eater",
    name: "噬光兽",
    onDeploy: [{ count: 1, kind: "damageHero" }],
    text: "降临：舔熄一寸光，灼伤你 1 点。",
    flavor: "光对它而言，是烫嘴的。",
  },
  {
    attack: 3,
    cost: 0,
    health: 2,
    icon: CARD_ICONS["blade-shadow"],
    id: "blade-shadow",
    keyword: "firstStrike",
    name: "刃影",
    text: "先手。它总比你的手快。",
  },
  {
    attack: 1,
    cost: 0,
    health: 4,
    icon: CARD_ICONS["mist-nightmare"],
    id: "mist-nightmare",
    name: "雾魇",
    text: "缠住灯火，让夜更稠。",
  },
  {
    attack: 2,
    cost: 0,
    health: 2,
    icon: CARD_ICONS["stitched-puppet"],
    id: "stitched-puppet",
    name: "缝傀儡",
    onDeploy: [{ count: 1, kind: "healHero" }],
    text: "降临：为深渊领主缝回 1 点魔魂。",
  },
  {
    attack: 3,
    cost: 0,
    health: 3,
    icon: CARD_ICONS["great-devourer"],
    id: "great-devourer",
    name: "巨噬",
    text: "它把整段黑暗咽了下去。",
  },
  {
    attack: 2,
    cost: 0,
    health: 2,
    icon: CARD_ICONS["night-owl"],
    id: "night-owl",
    name: "夜枭",
    onDeploy: [{ count: 1, kind: "damageHero" }],
    text: "降临：扑灭灯花，灼伤你 1 点。",
  },
  {
    attack: 1,
    cost: 0,
    health: 5,
    icon: CARD_ICONS["shadow-binder"],
    id: "shadow-binder",
    name: "缚影",
    text: "长长的影须，缠住一切。",
  },
];
