export const MAP_NODES = [
  {
    id: "node-1",
    label: "第一章",
    title: "东疆剿匪，心生疑云",
    kind: "battle",
    x: 18,
    y: 68,
    storyTitle: "第一章 · 东疆剿匪，心生疑云",
    story: [
      "节点1剧情1：雾中的脚步还没有远去。",
      "节点1剧情2：你要在破损的桥头继续前行。",
      "节点1剧情3：这是一场临时决定，也是一场逃离黑夜的试炼。",
    ],
    choices: [
      {
        id: "node-1-choice-1",
        title: "节点1选项1",
        description: "节点1选项1的描述：你选择稳住阵脚。",
        healthCost: 2,
        reward: "节点1卡牌占位1",
        aftermath: "节点1选项1结局：你稳住了脚步，前路不再那么模糊。",
      },
      {
        id: "node-1-choice-2",
        title: "节点1选项2",
        description: "节点1选项2的描述：你冲向最亮的那一段路。",
        healthCost: 3,
        reward: "节点1卡牌占位2",
        aftermath: "节点1选项2结局：你奔向亮处，却也失去了一部分力量。",
      },
      {
        id: "node-1-choice-3",
        title: "节点1选项3",
        description: "节点1选项3的描述：你选择不冒险，保持余力。",
        healthCost: 0,
        reward: "节点1卡牌占位3",
        aftermath: "节点1选项3结局：你保留了力气，也保留了未知的后果。",
      },
    ],
  },
  {
    id: "node-2",
    label: "第二章（查账线）",
    title: "账簿露秘，祸起高堂（查账线）",
    kind: "battle",
    x: 38,
    y: 42,
    storyTitle: "第二章 · 账簿露秘，祸起高堂（查账线）",
    branch: "audit",
    story: [
      "阿尔德里克押解俘虏返回城堡。晨雾未散，城门刚开，公爵的管家已经等在门口。",
      "“爵士辛苦了。公爵大人有令，匪患既平，俘虏交予城堡地牢处置。您连日奔波，请先回府歇息。”",
      "阿尔德里克勒住马，看了一眼身后五花大绑的小头目。对方也正看着他，眼神里没有求救，只有一种‘早知如此’的平静。",
      "“俘虏口供尚未录完。我要亲自审问。”管家却说，公爵认为匪寇狡诈，口供多有编造，自有专人料理。小头目被拖走前低声说：‘西边山道，夜半，鹰徽。’",
      "三日后，阿尔德里克以私访民情为名离开城堡，来到东部村镇。他在旧商人铺中查到了一本账册：每次村落报匪前夜，公爵私库都有一笔恰好够雇匪众的粮食采买支出。",
      "商人匆匆离去，街口却传来整齐的脚步声。公爵私兵到了。",
    ],
    choices: [
      {
        id: "node-2-choice-1",
        title: "节点2选项1",
        description: "节点2选项1的描述：你沿着回声寻找隐藏的出口。",
        healthCost: 2,
        reward: "节点2卡牌占位1",
        aftermath: "节点2选项1结局：回声引你迈向一条更窄的路。",
      },
      {
        id: "node-2-choice-2",
        title: "节点2选项2",
        description: "节点2选项2的描述：你拔刀，直接切开前方的死寂。",
        healthCost: 4,
        reward: "节点2卡牌占位2",
        aftermath: "节点2选项2结局：你穿过了死寂，但代价也被记在了身体上。",
      },
      {
        id: "node-2-choice-3",
        title: "节点2选项3",
        description: "节点2选项3的描述：你沉默着，先听一听下方是否有盲流。",
        healthCost: 1,
        reward: "节点2卡牌占位3",
        aftermath: "节点2选项3结局：你听见了来自深处的轻声，才决定继续。",
      },
    ],
  },
  {
    id: "rebel-2",
    label: "第二章（叛徒线）",
    title: "边境异动，蛮族南侵（叛徒线）",
    kind: "battle",
    x: 38,
    y: 78,
    storyTitle: "第二章 · 边境异动，蛮族南侵（叛徒线）",
    branch: "traitor",
    story: [
      "阿尔德里克收编匪众后返回城堡复命，雷纳德公爵和颜悦色，当众褒奖。次日，新令下达——追杀一名逃往滨海领的叛誓骑士。",
      "阿尔德里克率小队沿边境线向滨海行军。沿途村庄屡遭劫掠，痕印不似人类所为。斥候回报：蛮族战团频频南下。",
      "阿尔德里克抵达受袭村庄，蛮族勇士焚烧屋舍，村民四散奔逃。俘虏供述他们因更强战团压迫而南迁，粮草断绝才劫掠边境。科尔低声提醒：这些蛮族若收编，比匪众更能打仗。",
    ],
    choices: [],
  },
  {
    id: "rebel-3",
    label: "第三章（叛徒线）",
    title: "叛徒线第三章",
    kind: "battle",
    x: 58,
    y: 82,
    storyTitle: "第三章 · 叛徒线",
    branch: "traitor",
    story: ["叛徒线第三章剧情待补充。"],
    choices: [],
  },
  {
    id: "rebel-4",
    label: "第四章（叛徒线）",
    title: "叛徒线第四章",
    kind: "battle",
    x: 78,
    y: 78,
    storyTitle: "第四章 · 叛徒线",
    branch: "traitor",
    story: ["叛徒线第四章剧情待补充。"],
    choices: [],
  },
  {
    id: "rebel-5",
    label: "第五章（叛徒线）",
    title: "叛徒线第五章",
    kind: "battle",
    x: 92,
    y: 66,
    storyTitle: "第五章 · 叛徒线",
    branch: "traitor",
    story: ["叛徒线第五章剧情待补充。"],
    choices: [],
  },
  {
    id: "node-3",
    label: "第三章（查账线）",
    title: "同袍无踪，荒冢无名（查账线）",
    kind: "battle",
    x: 58,
    y: 56,
    storyTitle: "第三章 · 同袍无踪，荒冢无名（查账线）",
    branch: "audit-chapter-3",
    story: [
      "阿尔德里克策马北上，抵达边陲军营。营门守将见他便神色慌张，匆匆入内通报。",
      "片刻后，一名自称‘代守将’的军官出迎，言辞闪烁，坚称佩特里爵士自愿北调戍边，半年前已调往更北的哨塔。",
      "夜里，阿尔德里克潜入军营后方。荒坡上一座新土孤坟，无碑无名，坟前枯草间遗落一枚残破的骑士纹章，正是佩特里的家徽。",
    ],
    choices: [
      {
        id: "node-3-choice-1",
        title: "挖掘坟墓，确认身份",
        description: "确认佩特里的身份，不让真相埋在荒冢之下。",
        healthCost: 0,
        reward: "knights-legacy",
        aftermath: "你掘开荒土，确认了佩特里的遗物。骑士遗志将继续守护你的道路。",
      },
      {
        id: "node-3-choice-2",
        title: "默立凭吊，记下位置",
        description: "不惊动军营，记下荒冢位置后继续追查。",
        healthCost: 0,
        reward: "northern-scout",
        aftermath: "你将荒冢位置记在心中。北境斥候会替你继续寻找真相。",
      },
      {
        id: "node-3-choice-3",
        title: "暂不惊动军营",
        description: "暂时收起纹章，等待更安全的时机。",
        healthCost: 0,
        reward: "northern-scout",
        aftermath: "你没有惊动任何人，只把位置牢牢记下。",
      },
    ],
  },
  {
    id: "node-4",
    label: "第四章（查账线）",
    title: "匪首落定，密诏昭然（查账线）",
    kind: "battle",
    x: 78,
    y: 32,
    storyTitle: "第四章 · 匪首落定，密诏昭然（查账线）",
    branch: "audit-chapter-4",
    story: [
      "阿尔德里克循着所有线索追至边境一处废弃猎庄。院中拴着几匹好马，屋内有灯火。",
      "他踢开木门时，老管家正在灯下写信，手边搁着一只打开的铁匣。老管家抬头，并不惊慌。",
      "“你来得比我想象中快。佩特里当年花了六个月才找到这里。”老管家吹响铜哨，暗处涌出数名护卫。",
      "阿尔德里克拔剑列阵，老管家退入屋内，下令格杀勿论。",
    ],
    choices: [
      {
        id: "node-4-choice-1",
        title: "节点4选项1",
        description: "节点4选项1的描述：你叫出门内的声音。",
        healthCost: 2,
        reward: "节点4卡牌占位1",
        aftermath: "节点4选项1结局：门缝里传来了模糊的回应。",
      },
      {
        id: "node-4-choice-2",
        title: "节点4选项2",
        description: "节点4选项2的描述：你直接破门而入。",
        healthCost: 4,
        reward: "节点4卡牌占位2",
        aftermath: "节点4选项2结局：门被你猛地推开，暴露出更深的黑暗。",
      },
      {
        id: "node-4-choice-3",
        title: "节点4选项3",
        description: "节点4选项3的描述：你站在门前，重新诵读誓言。",
        healthCost: 0,
        reward: "节点4卡牌占位3",
        aftermath: "节点4选项3结局：誓言重新被看见，门也轻轻向内让开。",
      },
    ],
  },
  {
    id: "node-6",
    label: "第六章",
    title: "真相大白（查账线）",
    kind: "battle",
    x: 92,
    y: 44,
    storyTitle: "第六章 · 真相大白（查账线）",
    story: [
      "东部匪患再起，规模更甚从前。阿尔德里克未经公爵调令，独自折返调查，发现山间盗匪被成体系地编组、配发兵器，绝非乌合之众。",
      "他顺藤摸瓜至一处隐蔽山谷，新匪首的营帐赫然立在谷中。掀帘入内，桌后端坐之人缓缓抬头——正是老管家。",
      "老管家见他并不意外：“公爵猜到你还会回来。这一回，不必留活口。”铜哨声起，四周伏兵齐出。",
    ],
    choices: [
      {
        id: "node-6-choice-1",
        title: "继续效忠，置若罔闻",
        description: "放下已经掌握的真相，继续服从公爵的命令。",
        healthCost: 0,
        reward: "none",
        aftermath: "你选择沉默，查账线在此锁定为愚忠结局。",
      },
      {
        id: "node-6-choice-2",
        title: "携证据归返，大殿对峙",
        description: "带着证据返回城堡，在大殿上当面对质。",
        healthCost: 0,
        reward: "butler-testimony",
        aftermath: "你握紧证据，决定让所有人听见老管家的口供。",
      },
      {
        id: "node-6-choice-3",
        title: "销毁所有证据，远走他乡",
        description: "销毁证据，离开这片被权力和谎言吞没的土地。",
        healthCost: 0,
        reward: "none",
        aftermath: "你烧掉证据，查账线在此锁定为归隐结局。",
      },
    ],
  },
];

export const MAP_ROUTES = [
  ["node-1", "node-2"],
  ["node-1", "rebel-2"],
  ["node-2", "node-3"],
  ["node-3", "node-4"],
  ["node-4", "node-6"],
  ["rebel-2", "rebel-3"],
  ["rebel-3", "rebel-4"],
  ["rebel-4", "rebel-5"],
];

export function getMapNode(nodeId) {
  return MAP_NODES.find((node) => node.id === nodeId) ?? MAP_NODES[0];
}

export function getMapNodeIndex(nodeId) {
  return MAP_NODES.findIndex((node) => node.id === nodeId);
}
