export const MAP_NODES = [
  {
    id: "node-1",
    label: "节点1",
    title: "断桥前哨",
    kind: "battle",
    x: 18,
    y: 68,
    storyTitle: "第 1 个节点 · 断桥前哨",
    story: [
      "节点1剧情1：雾中的脚步还没有远去。",
      "节点1剧情2：你要在破损的桥头继续前行。",
      "节点1剧情3：这是一场临时决定，也是一场逃离黑夜的试炼。",
    ],
    choices: [
      {
        id: "node-1-choice-1",
        title: "节点1选项1",
        description: "节点1选项1的描述：你选择稳住阵脚。",
        healthCost: 2,
        reward: "节点1卡牌占位1",
        aftermath: "节点1选项1结局：你稳住了脚步，前路不再那么模糊。",
      },
      {
        id: "node-1-choice-2",
        title: "节点1选项2",
        description: "节点1选项2的描述：你冲向最亮的那一段路。",
        healthCost: 3,
        reward: "节点1卡牌占位2",
        aftermath: "节点1选项2结局：你奔向亮处，却也失去了一部分力量。",
      },
      {
        id: "node-1-choice-3",
        title: "节点1选项3",
        description: "节点1选项3的描述：你选择不冒险，保持余力。",
        healthCost: 0,
        reward: "节点1卡牌占位3",
        aftermath: "节点1选项3结局：你保留了力气，也保留了未知的后果。",
      },
    ],
  },
  {
    id: "node-2",
    label: "节点2",
    title: "灰烬隧道",
    kind: "battle",
    x: 38,
    y: 42,
    storyTitle: "第 2 个节点 · 灰烬隧道",
    story: [
      "节点2剧情1：隧道中有低沉的回响，像巨大的呼吸。",
      "节点2剧情2：每一步都像踩过遗留下来的旧伤口。",
      "节点2剧情3：你知道，这里不是终点，只是更深的一层。",
    ],
    choices: [
      {
        id: "node-2-choice-1",
        title: "节点2选项1",
        description: "节点2选项1的描述：你沿着回声寻找隐藏的出口。",
        healthCost: 2,
        reward: "节点2卡牌占位1",
        aftermath: "节点2选项1结局：回声引你迈向一条更窄的路。",
      },
      {
        id: "node-2-choice-2",
        title: "节点2选项2",
        description: "节点2选项2的描述：你拔刀，直接切开前方的死寂。",
        healthCost: 4,
        reward: "节点2卡牌占位2",
        aftermath: "节点2选项2结局：你穿过了死寂，但代价也被记在了身体上。",
      },
      {
        id: "node-2-choice-3",
        title: "节点2选项3",
        description: "节点2选项3的描述：你沉默着，先听一听下方是否有盲流。",
        healthCost: 1,
        reward: "节点2卡牌占位3",
        aftermath: "节点2选项3结局：你听见了来自深处的轻声，才决定继续。",
      },
    ],
  },
  {
    id: "node-3",
    label: "节点3",
    title: "风暴裂口",
    kind: "battle",
    x: 58,
    y: 56,
    storyTitle: "第 3 个节点 · 风暴裂口",
    story: [
      "节点3剧情1：裂口中翻卷的风仿佛在吞没记忆。",
      "节点3剧情2：你必须在吹散的灰烬和伸出的黑影之间做出判断。",
      "节点3剧情3：这里的每一秒都像在消耗你的信念。",
    ],
    choices: [
      {
        id: "node-3-choice-1",
        title: "节点3选项1",
        description: "节点3选项1的描述：你先救下无路可退的人。",
        healthCost: 3,
        reward: "节点3卡牌占位1",
        aftermath: "节点3选项1结局：你把人带到了更安全的地带。",
      },
      {
        id: "node-3-choice-2",
        title: "节点3选项2",
        description: "节点3选项2的描述：你试图打断风暴的源头。",
        healthCost: 5,
        reward: "节点3卡牌占位2",
        aftermath: "节点3选项2结局：风暴被撕开了一条缝，但你也几乎耗尽了体力。",
      },
      {
        id: "node-3-choice-3",
        title: "节点3选项3",
        description: "节点3选项3的描述：你选择等待，观察黑暗在何处露出破绽。",
        healthCost: 1,
        reward: "节点3卡牌占位3",
        aftermath: "节点3选项3结局：你终于等到了一瞬间的弱点。",
      },
    ],
  },
  {
    id: "node-4",
    label: "节点4",
    title: "遗迹守门",
    kind: "battle",
    x: 78,
    y: 32,
    storyTitle: "第 4 个节点 · 遗迹守门",
    story: [
      "节点4剧情1：遗迹的门扉像一张慢慢闭合的眼睛。",
      "节点4剧情2：这不是普通的守门，而是某种被遗弃的誓约。",
      "节点4剧情3：在门后发亮的，是你早以为已经失去的希望。",
    ],
    choices: [
      {
        id: "node-4-choice-1",
        title: "节点4选项1",
        description: "节点4选项1的描述：你叫出门内的声音。",
        healthCost: 2,
        reward: "节点4卡牌占位1",
        aftermath: "节点4选项1结局：门缝里传来了模糊的回应。",
      },
      {
        id: "node-4-choice-2",
        title: "节点4选项2",
        description: "节点4选项2的描述：你直接破门而入。",
        healthCost: 4,
        reward: "节点4卡牌占位2",
        aftermath: "节点4选项2结局：门被你猛地推开，暴露出更深的黑暗。",
      },
      {
        id: "node-4-choice-3",
        title: "节点4选项3",
        description: "节点4选项3的描述：你站在门前，重新诵读誓言。",
        healthCost: 0,
        reward: "节点4卡牌占位3",
        aftermath: "节点4选项3结局：誓言重新被看见，门也轻轻向内让开。",
      },
    ],
  },
  {
    id: "node-5",
    label: "节点5",
    title: "深渊终点",
    kind: "battle",
    x: 88,
    y: 62,
    storyTitle: "第 5 个节点 · 深渊终点",
    story: [
      "节点5剧情1：这里没有更多的路可退。",
      "节点5剧情2：每一寸空气都像在等你承认自己的选择。",
      "节点5剧情3：如果你能够走到这里，就必须证明自己足以守住这一切。",
    ],
    choices: [
      {
        id: "node-5-choice-1",
        title: "节点5选项1",
        description: "节点5选项1的描述：你以最后的力量迎接对手。",
        healthCost: 4,
        reward: "节点5卡牌占位1",
        aftermath: "节点5选项1结局：你按住了尚未散去的黑影。",
      },
      {
        id: "node-5-choice-2",
        title: "节点5选项2",
        description: "节点5选项2的描述：你牺牲速度，换取更稳的防守。",
        healthCost: 3,
        reward: "节点5卡牌占位2",
        aftermath: "节点5选项2结局：你守住了阵线，站到了最深处。",
      },
      {
        id: "node-5-choice-3",
        title: "节点5选项3",
        description: "节点5选项3的描述：你将所有信念压进最后一击。",
        healthCost: 5,
        reward: "节点5卡牌占位3",
        aftermath: "节点5选项3结局：这最后一击终于让黑暗沉默。",
      },
    ],
  },
];

export function getMapNode(nodeId) {
  return MAP_NODES.find((node) => node.id === nodeId) ?? MAP_NODES[0];
}

export function getMapNodeIndex(nodeId) {
  return MAP_NODES.findIndex((node) => node.id === nodeId);
}
